---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
    update_cache: "yes"

- name: Install Docker key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0664'
  become: true
  changed_when: false

- name: Dearmor docker.asc
  ansible.builtin.shell:
    cmd: >
      cat /etc/apt/trusted.gpg.d/docker.asc | gpg --dearmor >
      /etc/apt/trusted.gpg.d/packages.docker.gpg
    creates: /etc/apt/trusted.gpg.d/packages.docker.gpg
  become: true

- name: Remove /etc/apt/trusted.gpg.d/docker.asc
  file:
    path: /etc/apt/trusted.gpg.d/docker.asc
    state: absent
  become: true
  changed_when: false

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/\
      packages.docker.gpg] https://download.docker.com/linux/\
      {{ ansible_distribution|lower }} {{ ansible_distribution_release }} \
      stable"

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: "yes"

- name: Add to the docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: "yes"

- name: Pull images
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - fedora:rawhide
    - ubuntu:rolling
